# 轨道配置
tracks:
  - id: "h1"
    type: "horizontal"
    start_pos: [7, 19]
    end_pos: [28, 19]
  - id: "h2"
    type: "horizontal"
    start_pos: [10, 15]
    end_pos: [19, 15]
  - id: "h3"
    type: "horizontal"
    start_pos: [1, 11]
    end_pos: [19, 11]
  - id: "h4"
    type: "horizontal"
    start_pos: [1, 3]
    end_pos: [19, 3]
  - id: "v1"
    type: "vertical"
    start_pos: [1, 3]
    end_pos: [1, 11]
  - id: "v2"
    type: "vertical"
    start_pos: [7, 3]
    end_pos: [7, 23]
  - id: "v3"
    type: "vertical"
    start_pos: [10, 3]
    end_pos: [10, 26]
  - id: "v4"
    type: "vertical"
    start_pos: [13, 3]
    end_pos: [13, 26]
  - id: "v5"
    type: "vertical"
    start_pos: [16, 3]
    end_pos: [16, 26]
  - id: "v6"
    type: "vertical"
    start_pos: [19, 3]
    end_pos: [19, 23]
  - id: "v7"
    type: "vertical"
    start_pos: [22, 19]
    end_pos: [22, 23]

# 车辆配置
vehicles:
  - id: "crane1_1"
    type: "crane"
    init_pos: [9, 19]
    track: "h1"
    connect_vehicles: ["trolley2_1", "trolley3_1", "trolley4_1", "trolley5_1", "trolley6_1", "trolley7_1"]
  - id: "crane1_2"
    type: "crane"
    init_pos: [18, 19]
    track: "h1"
    connect_vehicles: ["trolley2_1", "trolley3_1", "trolley4_1", "trolley5_1", "trolley6_1", "trolley7_1"]
  - id: "crane2_1"
    type: "crane"
    init_pos: [12, 15]
    track: "h2"
    connect_vehicles: ["trolley3_1", "trolley4_1", "trolley5_1", "trolley6_1"]
  - id: "crane3_1"
    type: "crane"
    init_pos: [12, 11]
    track: "h3"
    connect_vehicles: ["trolley1_1", "trolley2_1", "trolley3_1", "trolley4_1", "trolley5_1", "trolley6_1"]
  - id: "crane4_1"
    type: "crane"
    init_pos: [11, 3]
    track: "h4"
    connect_vehicles: ["trolley1_1", "trolley2_1", "trolley3_1", "trolley4_1", "trolley5_1", "trolley6_1"]
  - id: "trolley1_1"
    type: "trolley"
    init_pos: [1, 5]
    track: "v1"
    connect_vehicles: ["crane3_1", "crane4_1"]
  - id: "trolley2_1"
    type: "trolley"
    init_pos: [7, 9]
    track: "v2"
    connect_vehicles: ["crane1_1", "crane1_2", "crane3_1", "crane4_1"]
  - id: "trolley3_1"
    type: "trolley"
    init_pos: [10, 7]
    track: "v3"
    connect_vehicles: ["crane1_1", "crane1_2", "crane2_1", "crane3_1", "crane4_1"]
  - id: "trolley4_1"
    type: "trolley"
    init_pos: [13, 7]
    track: "v4"
    connect_vehicles: ["crane1_1", "crane1_2", "crane2_1", "crane3_1", "crane4_1"]
  - id: "trolley5_1"
    type: "trolley"
    init_pos: [16, 22]
    track: "v5"
    connect_vehicles: ["crane1_1", "crane1_2", "crane2_1", "crane3_1", "crane4_1"]
  - id: "trolley6_1"
    type: "trolley"
    init_pos: [19, 13]
    track: "v6"
    connect_vehicles: ["crane1_1", "crane1_2", "crane2_1", "crane3_1", "crane4_1"]
  - id: "trolley7_1"
    type: "trolley"
    init_pos: [22, 21]
    track: "v7"
    connect_vehicles: ["crane1_1", "crane1_2"]

workstations:
  # 加工工位配置
  - id: "1LD"
    type: "processing"
    pos: [10, 26]
    connected_tracks: ["v3"]
  - id: "2LD"
    type: "processing"
    pos: [13, 26]
    connected_tracks: ["v4"]
  - id: "3LD"
    type: "processing"
    pos: [16, 26]
    connected_tracks: ["v5"]
  - id: "1LF"
    type: "processing"
    pos: [7, 23]
    connected_tracks: ["v2"]
  - id: "2LF"
    type: "processing"
    pos: [7, 7]
    connected_tracks: ["v2"]
  - id: "4LF"
    type: "processing"
    pos: [19, 23]
    connected_tracks: ["v6"]
  - id: "1RH"
    type: "processing"
    pos: [19, 7]
    connected_tracks: ["v6"]
  - id: "2RH"
    type: "processing"
    pos: [22, 23]
    connected_tracks: ["v7"]
  - id: "4RH"
    type: "processing"
    pos: [1, 7]
    connected_tracks: ["v1"]
  - id: "1CC"
    type: "processing"
    pos: [25, 19]
    connected_tracks: ["h1"]
  - id: "2CC"
    type: "processing"
    pos: [28, 19]
    connected_tracks: ["h1"]
  - id: "3CC"
    type: "processing"
    pos: [4, 3]
    connected_tracks: ["h4"]
  # 交互工位配置
  - id: "1LF1"
    type: "interaction"
    pos: [7, 19]
    connected_tracks: ["h1", "v2"]
  - id: "2LF3"
    type: "interaction"
    pos: [7, 11]
    connected_tracks: ["h3", "v2"]
  - id: "2LF5"
    type: "interaction"
    pos: [7, 3]
    connected_tracks: ["h4", "v2"]
  - id: "1LD1"
    type: "interaction"
    pos: [10, 19]
    connected_tracks: ["h1", "v3"]
  - id: "1LD2"
    type: "interaction"
    pos: [10, 15]
    connected_tracks: ["h2", "v3"]
  - id: "1LD3"
    type: "interaction"
    pos: [10, 11]
    connected_tracks: ["h3", "v3"]
  - id: "1LD5"
    type: "interaction"
    pos: [10, 3]
    connected_tracks: ["h4", "v3"]
  - id: "2LD1"
    type: "interaction"
    pos: [13, 19]
    connected_tracks: ["h1", "v4"]
  - id: "2LD2"
    type: "interaction"
    pos: [13, 15]
    connected_tracks: ["h2", "v4"]
  - id: "2LD3"
    type: "interaction"
    pos: [13, 11]
    connected_tracks: ["h3", "v4"]
  - id: "2LD5"
    type: "interaction"
    pos: [13, 3]
    connected_tracks: ["h4", "v4"]
  - id: "3LD1"
    type: "interaction"
    pos: [16, 19]
    connected_tracks: ["h1", "v5"]
  - id: "3LD2"
    type: "interaction"
    pos: [16, 15]
    connected_tracks: ["h2", "v5"]
  - id: "3LD3"
    type: "interaction"
    pos: [16, 11]
    connected_tracks: ["h3", "v5"]
  - id: "3LD5"
    type: "interaction"
    pos: [16, 3]
    connected_tracks: ["h4", "v5"]
  - id: "1RH1"
    type: "interaction"
    pos: [19, 19]
    connected_tracks: ["h1", "v6"]
  - id: "1RH2"
    type: "interaction"
    pos: [19, 15]
    connected_tracks: ["h2", "v6"]
  - id: "1RH3"
    type: "interaction"
    pos: [19, 11]
    connected_tracks: ["h3", "v6"]
  - id: "1RH5"
    type: "interaction"
    pos: [19, 3]
    connected_tracks: ["h4", "v6"]
  - id: "2RH1"
    type: "interaction"
    pos: [22, 19]
    connected_tracks: ["h1", "v7"]
  - id: "4RH3"
    type: "interaction"
    pos: [1, 11]
    connected_tracks: ["h3", "v1"]
  - id: "4RH5"
    type: "interaction"
    pos: [1, 3]
    connected_tracks: ["h4", "v1"]
